# =============================================================
# ROS2 Humble Dockerfile
# Generated by ros2-dockergen v1.2.0
# =============================================================

FROM osrf/ros:humble-desktop

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]

# ── Upgrade to desktop-full ─────────────────────────────────
RUN apt-get update && apt-get install -y \
    ros-humble-desktop-full \
    && rm -rf /var/lib/apt/lists/*

# ── Locale ───────────────────────────────────────────────────
RUN apt-get update && apt-get install -y locales && \
    locale-gen en_US en_US.UTF-8 && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
    rm -rf /var/lib/apt/lists/*
ENV LANG=en_US.UTF-8

# ── System packages ──────────────────────────────────────────
RUN apt-get update && apt-get install -y \
    software-properties-common \
    apt-transport-https \
    ca-certificates \
    python3 \
    python3-pip \
    python3-venv \
    python3-setuptools \
    git \
    x11-apps \
    libx11-dev \
    mesa-utils \
    libgl1 \
    libglvnd-dev \
    libegl1 \
    libgl1-mesa-dri \
    cmake \
    build-essential \
    gcc \
    g++ \
    tmux \
    nano \
    vim \
    gdb \
    gdbserver \
    net-tools \
    iproute2 \
    iputils-ping \
    curl \
    wget \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# ── ROS2 build tools ─────────────────────────────────────────
RUN apt-get update && apt-get install -y \
    python3-rosinstall-generator \
    python3-colcon-common-extensions \
    python3-colcon-mixin \
    python3-rosdep \
    && rm -rf /var/lib/apt/lists/*

RUN rosdep init || true && rosdep update --rosdistro humble

# ── Zsh + Oh-My-Zsh ──────────────────────────────────────────
RUN apt-get update && apt-get install -y zsh && rm -rf /var/lib/apt/lists/*

# ── ROS2 packages ────────────────────────────────────────────
RUN apt-get update && apt-get install -y \
    ros-humble-rviz2 \
    ros-humble-rviz-common \
    ros-humble-gazebo-ros-pkgs \
    ros-humble-gazebo-ros2-control \
    ros-humble-navigation2 \
    ros-humble-nav2-bringup \
    ros-humble-slam-toolbox \
    ros-humble-cartographer \
    ros-humble-cartographer-ros \
    ros-humble-turtlebot3 \
    ros-humble-turtlebot3-msgs \
    ros-humble-turtlebot3-simulations \
    ros-humble-cv-bridge \
    ros-humble-image-transport \
    python3-opencv \
    ros-humble-perception-pcl \
    ros-humble-pcl-ros \
    ros-humble-joint-state-publisher \
    ros-humble-joint-state-publisher-gui \
    ros-humble-xacro \
    && rm -rf /var/lib/apt/lists/*

ENV GAZEBO_PLUGIN_PATH=$GAZEBO_PLUGIN_PATH:/opt/ros/humble/lib

ENV TURTLEBOT3_MODEL=waffle_pi

# ── SSH server ────────────────────────────────────────────────
RUN apt-get update && apt-get install -y openssh-server && \
    mkdir /var/run/sshd && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    rm -rf /var/lib/apt/lists/*
EXPOSE 22

# ── Non-root user ────────────────────────────────────────────
ARG UID=1000
ARG GID=1000
RUN if getent group ${GID} >/dev/null; then \
        groupmod -n adml $(getent group ${GID} | cut -d: -f1); \
    else groupadd -g ${GID} adml; fi && \
    if getent passwd ${UID} >/dev/null; then \
        usermod -l adml -m -d /home/adml $(getent passwd ${UID} | cut -d: -f1); \
    else useradd -m -u ${UID} -g ${GID} -s /bin/bash adml; fi
RUN echo "adml ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN mkdir -p /home/adml/ros2_ws/src && chown -R adml:adml /home/adml/ros2_ws

USER adml
WORKDIR /home/adml/ros2_ws

RUN export HOME=/home/adml && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# ── Shell setup ───────────────────────────────────────────────
RUN echo "source /opt/ros/humble/setup.bash" >> /home/adml/.bashrc
RUN echo 'export GAZEBO_PLUGIN_PATH=$GAZEBO_PLUGIN_PATH:/opt/ros/humble/lib' >> /home/adml/.bashrc
RUN echo 'export TURTLEBOT3_MODEL=waffle_pi' >> /home/adml/.bashrc
RUN echo "source /opt/ros/humble/setup.bash" >> /home/adml/.zshrc
RUN echo 'export GAZEBO_PLUGIN_PATH=$GAZEBO_PLUGIN_PATH:/opt/ros/humble/lib' >> /home/adml/.zshrc
RUN echo 'export TURTLEBOT3_MODEL=waffle_pi' >> /home/adml/.zshrc

ENV LANG=en_US.UTF-8

ENV QT_X11_NO_MITSHM=1

CMD ["/bin/bash"]
